try:
    from setuptools import setup, find_packages
except ImportError:
    from distribute_setup import use_setuptools

    use_setuptools()
    from setuptools import setup, find_packages

setup(
    name='django-linestripper',
    version='0.1.1',
    description="Removes blank / empty / whitespaced lines generated by template tags.",
    keywords='django beautiful blank',
    packages=['django_linestripper'],
    include_package_data=True,
    classifiers=[
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 2.7",
        "Operating System :: OS Independent",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
)
